site_name: Hongnan G. Machine Learning Blog
site_url: https://reighns92.github.io/reighns-ml-blog # change ghnreighns to reigHns92 for my new github acc
nav:
  - Home: index.md
  - About: about.md
  # - Getting Started: 
  #   - Workflow: getting_started.md
  #   - git: git.md
  # - Misc:
  #   - GCP: misc/gcp.md
  - Mathematics:
    - Linear Algebra:
      - Preliminaries: 
        - Lines and Planes: math/linear_algebra/preliminaries_lines_and_planes.md
      - Fields: mathematics/linear_algebra/00_linear_algebra_fields.md
      - Vectors:
        - Vector Operations: mathematics/linear_algebra/01_linear_algebra_vectors.md
        - Vector Products:
          - Linear Combination: mathematics/linear_algebra/02_linear_algebra_vectors_linear_combination.md
          - Dot Product: mathematics/linear_algebra/02_linear_algebra_vectors_dot_product.md
          - Outer Product: mathematics/linear_algebra/02_linear_algebra_vectors_outer_product.md
          - Unit Vector: mathematics/linear_algebra/02_linear_algebra_vectors_unit_vector.md
          - Exercises: mathematics/linear_algebra/02_linear_algebra_vectors_exercises.md
        - Vector Spaces: 
          - Vector Space and Subspaces: mathematics/linear_algebra/03_linear_algebra_vector_spaces_vector_subspaces.md
          - Vector Span: mathematics/linear_algebra/03_linear_algebra_vector_spaces_vector_span.md
          - Linear Independence: mathematics/linear_algebra/03_linear_algebra_vector_spaces_linear_independence.md
          - Basis and Dimension: mathematics/linear_algebra/03_linear_algebra_vector_spaces_basis_dimension.md
      - Matrix:
        - Matrix: mathematics/linear_algebra/04_linear_algebra_matrix.md
        - Basic Matrix Types: mathematics/linear_algebra/04_linear_algebra_matrix_basic_matrix_types.md
        - Basic Matrix Operations: mathematics/linear_algebra/04_linear_algebra_matrix_basic_operations.md
        - Matrix Multiplication: mathematics/linear_algebra/04_linear_algebra_matrix_multiplication.md
      - Matrix Theory:
        - Matrix Spaces: mathematics/linear_algebra/05_linear_algebra_matrix_theory_matrix_spaces.md  
        - Matrix Rank: mathematics/linear_algebra/05_linear_algebra_matrix_theory_matrix_rank.md
        - Row Elimination Preserves Column/Row Rank: mathematics/linear_algebra/05_linear_algebra_row_elimination_preserves_row_column_spaces_dependency.md
      - Linear Transformation:
        - Linear Transformation: mathematics/linear_algebra/linear_algebra_linear_transformations.md
      - Interview: mathematics/linear_algebra/linear_algebra_interview_questions.md

  # - Machine Learning Metrics: 
  #   - Classification:
  #     - Introduction: metrics/classification_metrics/classification_metrics.md
  #     - Accuracy: metrics/classification_metrics/accuracy.md
  #     - Confusion Matrix: metrics/classification_metrics/confusion_matrix.md
  #     - Precision-Recall-F1: metrics/classification_metrics/precision_recall_f1.md
  #     - ROC and PR Curves: metrics/classification_metrics/roc_pr_curve.md
  #     - Cohen's Kappa: metrics/classification_metrics/cohens_kappa.md
  #   - Regression:
  #     - Introduction: metrics/regression_metrics/dummy_file.md
  # - Machine Learning:
  #   - Supervised Learning Theory:
  #     - Regression: about.md
  #     - Classification:
  #       - Projects:
  #         - Breast Cancer Wisconsin:
  #           - Introduction: supervised_learning/classification/breast_cancer_wisconsin/Stage 0 - Introduction and Problem Statement.md
  #           - Preliminary Data Inspection and Cleaning: supervised_learning/classification/breast_cancer_wisconsin/Stage 1 - Preliminary Data Inspection and Cleaning.md
  #           - EDA: supervised_learning/classification/breast_cancer_wisconsin/Stage 2 - Preliminary EDA.md
  #           - Feature Engineering: supervised_learning/classification/breast_cancer_wisconsin/Stage 3 - Feature Engineering.md
  #           - Modelling (Metrics): supervised_learning/classification/breast_cancer_wisconsin/Stage 4 - Modelling (Metric to Optimize).md
  #           - Modelling (Cross-Validation Schema): supervised_learning/classification/breast_cancer_wisconsin/Stage 5 - Modelling (Cross-Validation Methodology).md
  #           - Modelling (Preprocessing and Spot Checking): supervised_learning/classification/breast_cancer_wisconsin/Stage 6 - Modelling (Preprocessing and Spot Checking).md
  #           - Modelling (Model Selection): supervised_learning/classification/breast_cancer_wisconsin/Stage 7 - Modelling (Model Selection and Hyperparameter Tuning).md
  #           - Modelling (Model Evaluation): supervised_learning/classification/breast_cancer_wisconsin/Stage 8 - Modelling (Model Evaluation and Interpretation).md
  - Deep Learning with PyTorch:
    - Computer Vision:
      - General: 
        - Visualizing Convolutional Filters: deep_learning/computer_vision/general/visualizing_convolutional_filters/Visualizing Convolutional Filters.md
theme:
  name: material
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
    - css/extra.css